### ISSUE TITLE
Téléchargement des plots et fichier final

### ISSUE THREAD

**Issue by amrocher** [llegregam/PascalTriangle#2]
Salut Loïc, 

Une fois MSPT lancé, je n'arrive pas à télécharger les plots, lorsque je clique sur "Save plots" ils me les affichent à nouveau en dessous mais aucun téléchargement ne démarre. Je peux en revanche les sauver un par un par un clic droit "Enregistrer l'image sous" mais c'est plus long !

Je n'ai pas non plus accès au fichier final avec les biais observés

![image](https://github.com/llegregam/PascalTriangle/assets/63723737/0644210d-7016-453d-aa61-4ec973fcadc4)

Merci :)

Amandine

**Comment by llegregam** [comment]
Il semblerait que le bug soit lié au même que dans issue #1 . Je vais regarder ça

**Comment by llegregam** [comment]
Couldn't reproduce, closing the issue
