### ISSUE TITLE
pb MSPT

### ISSUE THREAD

**Issue by Nina-LaLa** [llegregam/PascalTriangle#3]
Salut Loïc, 
Je n'arrive pas à obtenir mes fichiers sorties MSPT. Je vais jusqu'à soumettre mon jeu de données. J'ai ça sur le code : 

![image](https://github.com/llegregam/PascalTriangle/assets/173243640/1b29afd1-43aa-4448-86b3-a888edb404b5)

Mais je n'ai rien dans mon dossier : 

![image](https://github.com/llegregam/PascalTriangle/assets/173243640/97d3d567-333e-45f9-ae77-be67e6d3162d)

Et il n' y a aucune visualisation possible en ligne, je reste au moment du chargement des data : 

![image](https://github.com/llegregam/PascalTriangle/assets/173243640/9b59cea8-0417-41ba-8f69-566db330a158)

++
Nina

**Comment by llegregam** [comment]
Alors par hasard est-ce que tu as réactivé les logs pour que tu puisses suivre ce qu'il se passe dans le notebook? Depuis la dernière version il faut les réactiver à la main

**Comment by Nina-LaLa** [comment]
Je ne sais pas^^ comment je fais ça ?

**Comment by llegregam** [comment]
Tu peux demander à Lindsay si elle est là elle sait comment faire, sinon je te montre tout à l'heure quand je passe au labo

**Comment by Nina-LaLa** [comment]
ca marche, elle n'est pas la et je suis en congès cette ap mais plus tard :) merci

**Comment by llegregam** [comment]
Fixed in release 1.1.0. Merci!
