### ISSUE TITLE
MSPT 

### ISSUE THREAD

**Issue by laraGales31390** [llegregam/PascalTriangle#4]
Bonjour Loic 
Est il possible d'avoir une selection automatique de l'ensemble des Mn des metabolites plutot que de les faire un par un ? 
![mspt-Mn](https://github.com/llegregam/PascalTriangle/assets/173771907/038d9c2f-bdb5-4634-979e-0bafbc8fb73f)

merci bcp !

**Comment by llegregam** [comment]
Je ne comprends pas exactement la question, faudra qu'on en parle demain!

**Comment by llegregam** [comment]
Done
